name: Github Context Practice

run-name: ${{github.actor}}
 
on: workflow_dispatch
 
jobs:

 run-github-context:

  runs-on: ubuntu-latest

  steps:

   - name: Github Context Exercise

     run: |

      echo "Github Action ${{github.action}}"

      echo "Github Action Path ${{github.action_path}}"

      echo "Github Action Ref ${{github.action_ref}}"

      echo "Github Action Repository ${{github.action_repository}}"

      echo "Github Action Action ${{github.action_action}}"

      echo "Github Action Status ${{github.action_status}}"

      echo "Github Actor Id ${{github.actor_id}}"

      echo "Github Api Url ${{github.api_url}}"

      echo "Github Base Ref ${{github.base_ref}}"

      echo "Github Env ${{github.env}}"

      echo "Github Event Name ${{github.event_name}}"

      echo "Github Event Path ${{github.event_path}}"

      echo "Github Head Ref ${{github.head_ref}}"

      echo "Github Job ${{github.job}}"

      echo "Github Path ${{github.path}}"

      echo "Github Ref ${{github.ref}}"

      echo "Github Ref Name ${{github.ref_name}}"

      echo "Github Ref Protected ${{github.ref_protected}}"

      echo "Github Ref Type ${{github.ref_type}}"

      echo "Github Repository ${{github.repository}}"

      echo "Github Repository Id ${{github.repository_id}}"

      echo "Github Repository Owner ${{github.repository_owner}}"

      echo "Github Repository Owner Id ${{github.repository_owner_id}}"

      echo "Github Repository Url ${{github.repository_url}}"

      echo "Github Retention Days ${{github.retention_days}}"

      echo "Github Run Attempt ${{github.run_attempt}}"

      echo "Github Run Id ${{github.run_id}}"

      echo "Github Run Number ${{github.run_number}}"

      echo "Github Secret Source ${{github.secret_source}}"

      echo "Github Server Url ${{github.server_url}}"

      echo "Github SHA ${{github.sha}}"

      echo "Github Token ${{github.token}}"

      echo "Github Workflow ${{github.workflow}}"

      echo "Github Workflow Ref ${{github.workflow_ref}}"

      echo "Github Workflow SHA ${{github.workflow_sha}}"

      echo "Github Workspace ${{github.workspace}}"
